###############################################################################
# Copyright (c) 2017-22, Lawrence Livermore National Security, LLC
# and RAJA Performance Suite project contributors.
# See the RAJAPerf/COPYRIGHT file for details.
#
# SPDX-License-Identifier: (BSD-3-Clause)
###############################################################################

# DESCRIPTION:
###############################################################################
# General GitLab pipelines configurations for supercomputers and Linux clusters
# at Lawrence Livermore National Laboratory (LLNL).
# This entire pipeline is LLNL-specific
#
# Important note: This file is a copy of the template provided by
# llnl/radiuss-shared-ci. It should not require any change from the project.
#
# Instead, each project should provide:
# - .gitlab/custom-variables.yml
# - .gitlab/custom-pipelines.yml
# - .gitlab/custom-jobs.yml
# - .gitlab/${MACHINE}-build-and-test-extra.yml
###############################################################################

# We organize the CI on Gitlab in sub-pipelines. Each sub-pipeline corresponds
# to a test phase on a given machine.

# High level stages
stages:
  - build-and-test

# Template for jobs triggering a build-and-test sub-pipelines:
.build-and-test:
  stage: build-and-test
  trigger:
    include:
      - local: '.gitlab/custom-jobs.yml'
      - project: 'radiuss/radiuss-shared-ci'
        ref: v2022.09.rc
        file: '${CI_MACHINE}-build-and-test.yml'
      - local: '.gitlab/${CI_MACHINE}-build-and-test-extra.yml'
    strategy: depend
    forward:
      pipeline_variables: true

# Import parameters and pipelines defined by the project
include:
  - local: .gitlab/custom-variables.yml
  - local: .gitlab/custom-pipelines.yml
